### CREATE five documents.
POST http://localhost:3000/albums HTTP/1.1
content-type: application/json

{
    "title": "Thriller",
    "artist": "Michael Jackson", 
    "releaseDate": "1982-11-29",
    "numberOfSongs": 9
}


### CREATE 2
POST http://localhost:3000/albums HTTP/1.1
content-type: application/json

{
    "title": "Back in Black",
    "artist": "AC/DC", 
    "releaseDate": "1980-07-25",
    "numberOfSongs": 10
}

### CREATE 3
POST http://localhost:3000/albums HTTP/1.1
content-type: application/json

{
    "title": "21",
    "artist": "Adele", 
    "releaseDate": "2011-01-24",
    "numberOfSongs": 11
}

### CREATE 4
POST http://localhost:3000/albums HTTP/1.1
content-type: application/json

{
    "title": "Abbey Road",
    "artist": "the Beatles", 
    "releaseDate": "1969-09-26",
    "numberOfSongs": 17
}

### CREATE 5
POST http://localhost:3000/albums HTTP/1.1
content-type: application/json

{
    "title": "Jagged Little Pill",
    "artist": "Alanis Morissette", 
    "releaseDate": "1995-06-13",
    "numberOfSongs": 13
}


### RETRIEVE all documents.
GET http://localhost:3000/albums HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/albums/64d069404bc78fcc91cdec9e HTTP/1.1


### UPDATE one document's year, by ID.
### Replace the ID in the following request with one that exists
### and update the title, artist, date of release, and/or number of songs.
### Date of release and number of songs updated for Adele album:
PUT http://localhost:3000/albums/64d0694b4bc78fcc91cdeca0 HTTP/1.1
content-type: application/json

{
    "title": "21",
    "artist": "Adele", 
    "releaseDate": "2011-02-22",
    "numberOfSongs": 15
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/albums/64d069404bc78fcc91cdec9e HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/albums HTTP/1.1

